---
name: ar_post
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  arkit_plugin: ^0.6.0
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  dartz: ^0.9.2
  equatable: ^1.2.5
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  flutter_bloc: ^6.1.1
  freezed_annotation: ^0.12.0
  get_it: ^5.0.3
  google_sign_in: ^4.5.9
  injectable: ^1.0.4
  uuid: ^2.2.2
  google_fonts: ^1.1.1
  screenshot: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  freezed: ^0.12.6
  injectable_generator: ^1.0.4
  lint: ^1.3.0
analyzer:
  exclude:
  - '**/*.g.dart'
  - '**/*.freezed.dart'
flutter:
  uses-material-design: true
